### PR TITLE
Optimize sen slope(), yielding identical results.

### PR DESCRIPTION
**Pull request by stasinos**
Commit 329da7de09246f648968b1477f96dbffca669e76 sorts the array of slopes and uses the sorted array to find slope, lcl, and ucl. This avoids sorting the same data multiple times.

Commit 3949249064686e6cdee374b90b18a0744b0c4fe6 changes the order of checking for NaNs and iterating through the obs array to create the array of all slopes. This avoids adding NaNs in the array of slopes just to remove them immediatelly afterwards.

The runtimes gains are significant. Here are the results on an i5-8400 @ 2.80GHz:

Using v1.1.0: 433.10 sec
After applying 329da7d "Avoid gratuitous sorting": 348.60 sec
After applying both patches: 248.31 sec

pytest log using v1.1.0:

============================================================== test session starts ===============================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/konstant/projects/atmo/dataeng-mannkendall
collected 16 items                                                                                                                               

test/test_mk_hardcoded.py .                                                                                                                [  6%]
test/test_mk_main.py ....                                                                                                                  [ 31%]
test/test_mk_stats.py ...                                                                                                                  [ 50%]
test/test_mk_tools.py ......                                                                                                               [ 87%]
test/test_mk_white.py ..                                                                                                                   [100%]

================================================================ warnings summary ================================================================
test/test_mk_main.py::test_mk_temp_aggr_single
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_main.py:371: UserWarning: The trends for the temporal aggregation are not homogenous.
    warnings.warn('The trends for the temporal aggregation are not homogenous.')

test/test_mk_white.py::test_nanprewhite_arok
test/test_mk_white.py::test_prewhite
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_white.py:94: UserWarning: No statistically significant autocorrelation.
    warnings.warn('No statistically significant autocorrelation.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================================== 16 passed, 3 warnings in 433.10s (0:07:13) ===================================================

pytest log after applying 329da7d:

============================================================== test session starts ===============================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/konstant/projects/atmo/dataeng-mannkendall
collected 16 items                                                                                                                               

test/test_mk_hardcoded.py .                                                                                                                [  6%]
test/test_mk_main.py ....                                                                                                                  [ 31%]
test/test_mk_stats.py ...                                                                                                                  [ 50%]
test/test_mk_tools.py ......                                                                                                               [ 87%]
test/test_mk_white.py ..                                                                                                                   [100%]

================================================================ warnings summary ================================================================
test/test_mk_main.py::test_mk_temp_aggr_single
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_main.py:371: UserWarning: The trends for the temporal aggregation are not homogenous.
    warnings.warn('The trends for the temporal aggregation are not homogenous.')

test/test_mk_white.py::test_nanprewhite_arok
test/test_mk_white.py::test_prewhite
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_white.py:94: UserWarning: No statistically significant autocorrelation.
    warnings.warn('No statistically significant autocorrelation.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================================== 16 passed, 3 warnings in 348.60s (0:05:48) ===================================================

pytest log after applying both:

============================================================== test session starts ===============================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/konstant/projects/atmo/dataeng-mannkendall
collected 16 items                                                                                                                               

test/test_mk_hardcoded.py .                                                                                                                [  6%]
test/test_mk_main.py ....                                                                                                                  [ 31%]
test/test_mk_stats.py ...                                                                                                                  [ 50%]
test/test_mk_tools.py ......                                                                                                               [ 87%]
test/test_mk_white.py ..                                                                                                                   [100%]

================================================================ warnings summary ================================================================
test/test_mk_main.py::test_mk_temp_aggr_single
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_main.py:371: UserWarning: The trends for the temporal aggregation are not homogenous.
    warnings.warn('The trends for the temporal aggregation are not homogenous.')

test/test_mk_white.py::test_nanprewhite_arok
test/test_mk_white.py::test_prewhite
  /home/konstant/projects/atmo/dataeng-mannkendall/src/mannkendall/mk_white.py:94: UserWarning: No statistically significant autocorrelation.
    warnings.warn('No statistically significant autocorrelation.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================================== 16 passed, 3 warnings in 248.31s (0:04:08) ===================================================

### CODE REVIEW

**Comment by fpavogt** [comment]
Hey @stasinos, thanks a lot for this PR ! The computational gain by not sorting everywhere is indeed significant. Since I'm currentlz preparing PR #34 to fix the docs (etc...), I'll point your PR to the `develop_vof` branch, and I'll then merge it all inside `develop` down the line.

@mcollaudcoen, I would be in favor of merging this contribution. But this would imply the existence of a first (very small, but still) code mismatch between the different implementations. Still, at roughly 50% speed gain, these changes have a very important effect, and no impact on the results themselves.

**Comment by fpavogt** [comment]
Thanks for the prompt update of the CHANGELOG ... and sorry about the resulting conflict. Feel free to simply undo that change, and I'll add your entry to the CHANGELOG myself.

**Comment by stasinos** [comment]
Fixed, no worries. If only all merges could be fixed like that.

**Review by fpavogt — APPROVED** [review]
Thanks for the input !

**Review by mcollaudcoen — APPROVED** [review]
My opinion is that minor changes between the languages are welcomed if the results are not modified. Thanks for the improvements of the code

**Pull request merged**
